version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Podmanfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    container_name: taxes-api
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: taxes
      DB_HOST: localhost
      DB_PORT: 5432
      SERVER_PORT: 8080
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: